# Generated by Django 3.2.13 on 2022-05-20 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('m', 'men'), ('w', 'women')], max_length=1)),
                ('birth_day', models.DateField()),
                ('phone', models.CharField(max_length=20)),
                ('national_id', models.CharField(max_length=20)),
                ('staffid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.detailuser')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
        ),
    ]
