# Generated by Django 3.2.13 on 2022-05-20 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_alter_detailuser_staffid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detailuser',
            options={'verbose_name': 'user-detail', 'verbose_name_plural': 'users-detail'},
        ),
        migrations.RemoveField(
            model_name='detailuser',
            name='staffid',
        ),
    ]
