# Generated by Django 3.2.13 on 2022-05-20 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_auto_20220521_0034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detailuser',
            options={'verbose_name': 'نام کاربر', 'verbose_name_plural': 'اطلاعات کاربران'},
        ),
        migrations.AlterModelOptions(
            name='userstaff',
            options={'verbose_name': 'نام کارمند', 'verbose_name_plural': 'اطلاعات کارمندان'},
        ),
    ]
