# Generated by Django 3.2.13 on 2022-05-20 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_auth', '0004_userstaff'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='borrower_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_from', models.DateField(blank=True, null=True)),
                ('borrowed_to', models.DateField(blank=True, null=True)),
                ('isbn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book_manager')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.detailuser')),
                ('userstaff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.userstaff')),
            ],
        ),
    ]
