# Generated by Django 3.2.13 on 2022-05-20 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrower', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrower_details',
            options={'verbose_name': 'تراکنش', 'verbose_name_plural': 'تراکنش ها'},
        ),
    ]
