# Generated by Django 3.2.13 on 2022-05-20 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='book_manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('book_title', models.CharField(max_length=8)),
                ('lang', models.CharField(max_length=5)),
                ('book_status', models.CharField(choices=[('borrowed', 'ناموجود'), ('in library', 'موجود')], max_length=10)),
                ('pub_year', models.DateField()),
                ('categoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
    ]
