# Generated by Django 3.2.13 on 2022-05-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_manager',
            name='book_status',
            field=models.CharField(choices=[('ناموجود', 'ناموجود'), ('موجود', 'موجود')], max_length=10),
        ),
    ]
