# Generated by Django 3.2.13 on 2022-05-20 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_manager_book_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book_manager',
            options={'verbose_name': 'کتاب', 'verbose_name_plural': 'کتاب ها'},
        ),
    ]
