# Generated by Django 3.2.13 on 2022-05-20 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_manager_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book_manager',
            options={'verbose_name': 'نام کتاب', 'verbose_name_plural': 'کتاب ها'},
        ),
        migrations.RenameField(
            model_name='book_manager',
            old_name='categoryid',
            new_name='category',
        ),
    ]
